FROM node:20-alpine
RUN apk add --no-cache openssl
USER root
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
EXPOSE 4000
CMD ["sh", "-c", "npx prisma generate && npx prisma migrate deploy && npm run start:dev"]
