(BigInt.prototype as any).toJSON = function () { return Number(this); };

import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import morgan from 'morgan';
import { errorHandler } from './middleware/error.middleware';
import healthRoutes from './api/v1/health.routes';
import aiRoutes from './api/v1/ai.routes';
import authRoutes from './api/v1/auth.routes';
import usersRoutes from './api/v1/users.routes';
import prospectsRoutes from './api/v1/prospects.routes';
import projectsRoutes from './api/v1/projects.routes';
import rksRoutes, { projectRksRouter } from './api/v1/rks.routes';
import lphsSiosRoutes, { projectLphsRouter } from './api/v1/lphs-sios.routes';
import hargaKompetitorRoutes, { projectHargaRouter } from './api/v1/harga-kompetitor.routes';
import pemenangDeliveryRoutes, { projectPemenangRouter } from './api/v1/pemenang-delivery.routes';
import approvalsRoutes from './api/v1/approvals.routes';
import documentsRoutes from './api/v1/documents.routes';
import dashboardRoutes from './api/v1/dashboard.routes';
import masterDataRoutes from './api/v1/master-data.routes';
import configRoutes from './api/v1/config.routes';
import notificationsRoutes from './api/v1/notifications.routes';
import reportsRoutes from './api/v1/reports.routes';
import auditRoutes from './api/v1/audit.routes';

const app = express();
app.use(helmet());
app.use(cors({ origin: process.env.FRONTEND_URL || 'http://localhost:3000', credentials: true }));
app.use(morgan('dev'));
app.use(express.json({ limit: '10mb' }));

app.use('/health', healthRoutes);
app.use('/api/v1/health', healthRoutes);
app.use('/api/v1/auth', authRoutes);
app.use('/api/v1/ai', aiRoutes);
app.use('/api/v1/users', usersRoutes);
app.use('/api/v1/prospects', prospectsRoutes);
app.use('/api/v1/projects', projectsRoutes);
app.use('/api/v1/rks', rksRoutes);
app.use('/api/v1/projects/:projectId/rks', projectRksRouter);
app.use('/api/v1/lphs-sios', lphsSiosRoutes);
app.use('/api/v1/projects/:projectId/lphs-sios', projectLphsRouter);
app.use('/api/v1/harga-kompetitor', hargaKompetitorRoutes);
app.use('/api/v1/projects/:projectId/harga-kompetitor', projectHargaRouter);
app.use('/api/v1/pemenang-delivery', pemenangDeliveryRoutes);
app.use('/api/v1/projects/:projectId/pemenang-delivery', projectPemenangRouter);
app.use('/api/v1/approvals', approvalsRoutes);
app.use('/api/v1/documents', documentsRoutes);
app.use('/api/v1/dashboard', dashboardRoutes);
app.use('/api/v1/master-data', masterDataRoutes);
app.use('/api/v1/config', configRoutes);
app.use('/api/v1/notifications', notificationsRoutes);
app.use('/api/v1/reports', reportsRoutes);
app.use('/api/v1/audit', auditRoutes);

app.use(errorHandler);
export default app;
